#!/system/bin/sh

INPUT=$1
echo "#include <Arduino.h>" > $INPUT.cpp
cat $INPUT >> $INPUT.cpp
$AVR_GXX -xc++ -I$ARDUINOCORE -I$ARDUINOLIBS -c $INPUT.cpp -o $INPUT.o
rm $INPUT.cpp
$AVR_LD -o $INPUT.elf $INPUT.o $ARDUINOLIBS/*.a $ARDUINOCORE/libcore.a
rm $INPUT.o
$AVR_STRIP -s -x -X $INPUT.elf
$AVR_MKHEX $INPUT.elf $INPUT.hex
rm $INPUT.elf
